In [20]:
import numpy as np

# Cadeias de Markov
São modelos matemáticos que descrevem a evolução de um sistema que passa sucessivamente por diferentes estados, onde cada estado seguinte é dependente do anterior imediato.

# 1. Prever o longo prazo

## 1.1. Modelo cássico: 2 estados

### **Previsão do Tempo**

- Sabendo que hoje está sol, o que devemos esperar daqui a dois dias?

![modelo_classico_2_estados](imagens/modelo_classico_2_estados.png)

In [21]:
# Matriz transição
M = np.array([[0.5, 0.3],
              [0.5, 0.7]]
            )
            
# Estado inicial
X0 = np.array([[1],[0]])

# 1 dia após
X1 = np.matmul(M,X0)
# 2 dias após
X2 = np.matmul(M,X1)

# 2 dias após pode ser calculado da forma
dias = 2
M_intermed = np.linalg.matrix_power(M,dias)
X2 = np.matmul(M_intermed,X0)

# Após 1 ano:
dias = 365
M_intermed = np.linalg.matrix_power(M,dias)
X1a = np.matmul(M_intermed,X0)

print(f'Matriz transição:\n{M}\nEstado inicial:\n{X0}\nApós 1 dia:\n{X1}\nApós 2 dias:\n{X2}\nApós 1 ano:\n{X1a}')

Matriz transição:
[[0.5 0.3]
 [0.5 0.7]]
Estado inicial:
[[1]
 [0]]
Após 1 dia:
[[0.5]
 [0.5]]
Após 2 dias:
[[0.4]
 [0.6]]
Após 1 ano:
[[0.375]
 [0.625]]


#### Observações
- Generalização do modelo: $$ X_k+_1 = MX_k $$
- Vetor estacionário (q) $$ Lim (k > inf) M^k = q $$
- Dias com nuvem após dias de sol são muito mais frequentes

### **Previsão de mobilidade**

- Sabendo que a distribuição da população em 2010 é: 5x10^6 na cidade e 1x10^6 nos arredores, qual será a distribuição em 2020?
- Matriz de transição =  matriz de mobilidade de 5 em 5 anos

![modelo_classico_2_estados_distribuicao_pop](imagens/modelo_classico_2_estados_distribuicao_pop.png)

In [22]:
# Matriz de mobilidade da população em 5 em 5 anos
M = np.array([[.7,.5],
              [.3,.5]]
            )

# Estados inicial
X0 = np.array([[5E6],
              [1E6]]
             )

# Distribuição em 2020:
# 10 anos de diferença = 2 passos de 5, logo:
X2 = np.matmul((np.linalg.matrix_power(M,2)),X0)
print(f'Após 10 anos:\n{X2}')

# Qual será a distribuição daqui a 100 anos? 
passo = int(100/5)
X100 = np.matmul((np.linalg.matrix_power(M,passo)),X0)
print(f'Após 100 anos:\n{X100}')

Após 10 anos:
[[3800000.]
 [2200000.]]
Após 100 anos:
[[3750000.00000001]
 [2249999.99999999]]


## 1.2. Modelo de 3 estados

### **Distribuição de bicicletas entre prédios da universidade**

- Dada matriz de transição, e, sabendo que 300 bicicletas serão distribuídas segundo matriz de estado inicial, avalie a distribuição das bicicletas a longo prazo.

![modelo_3_estados_distrib_bikes](imagens/modelo_3_estados_distrib_bikes.png)

In [23]:
# Distribuição de bicicletas entre os prédios da universidade
M = np.array([[.95,.02,.05],
              [.03,.9,.05],
              [.02,.08,.9]
             ])
# 300 Bicicletas distribuídas na 2ª feira nas seguintes frações:
X0 = np.array([[.5],
               [.3],
               [.2]
              ])
# Distribuição na segunda (para comparação)
print('Distribuição na segunda feira:','\n',X0*300)

# Distribuição na quinta feira
passo = 3
X3 = np.matmul((np.linalg.matrix_power(M,passo)),X0)

# Necessário multiplicar pelas 300 bicicletas disponíveis para encontrar a distribuição real
X3 = X3*300
print('Distribuição na quinta feira:','\n',X3)

# Obtendo a distribuição estável a longo prazo
passo = 100
X_longo = np.matmul((np.linalg.matrix_power(M,passo)),X0)
# Multiplicar pelas 300 bicicletas disponíveis
X_longo = X_longo*300
print('Distribuição a longo prazo:','\n',X_longo)

Distribuição na segunda feira: 
 [[150.]
 [ 90.]
 [ 60.]]
Distribuição na quinta feira: 
 [[142.80513]
 [ 86.28885]
 [ 70.90602]]
Distribuição a longo prazo: 
 [[125.00148948]
 [ 83.33283724]
 [ 91.66567328]]


## Exercícios

### 1.1 Previsão de estado

![Alt text](imagens/exercicio_1-1_previsao_de_estado.png)

In [24]:
# Questão 1 - Previsão de estado
#Um dado processo de Markov com dois estados encontra-se inicialmente no estado 1 e sabe-se que a matriz de transição da cadeia é dada por:
M = np.array([[1/2,9/14],
              [1/2,5/14]
             ])
X0 = np.array([[1],
               [0]
              ])
# Qual a probabilidade da cadeia se encontrar no estado 2 decorridas exatamente 4 transições?
transicoes = 4
M4 = np.linalg.matrix_power(M,transicoes)
X4 = np.matmul(M4,X0)
print(X4)

[[0.56268222]
 [0.43731778]]


### 1.2. Matriz de transição

![Alt text](imagens/exercicio_1-2.png)

In [25]:
# Questão 2 - Matriz de transição
# Num dado país, as votações estão há vários anos bipolarizadas em dois partidos políticos, o PDC e o BEL. De 4 em 4 anos, a percentagem de votantes no PDC que continua a votar em PDC é de 55%, enquanto 45% dos anteriores votos no PCD passam para o BEL. Por outro lado, nesse mesmo período, há 50% de votos no BEL que são deslocados para votos no PDC e os restantes 50% permanecem votos no BEL.

# Qual a matriz de transição do voto eleitoral no país em causa?
M = np.array([[.55,.50],
              [.45,.50]
             ])
print(M)

[[0.55 0.5 ]
 [0.45 0.5 ]]


### 1.3. Previsão de tempo

![Alt text](imagens/exercicio_1-3.png)

In [26]:
# Questão 3 - Previsão de tempo
# Numa dada região, o clima alterna anualmente de acordo com o seguinte modelo. Cada ano, a probabilidade de vir um ano seco a seguir a um ano sem chuva é de 55%, e a de vir um ano de chuvas a seguir a um ano seco é de 45%. Por outro lado, anualmente, há 50% de probabilidade de a seguir a um ano de chuvas vir um ano de seca e 50% de vir um ano de chuvas após um ano de chuvas.

# Suponha que a previsão para 2016 era de 40% de ano seco e de 60% de chuvas fortes.

# Qual a distribuição de previsão do tempo para 2020?
#             Seco|Chuva
M= np.array([[1-.45,.50], # Seco
             [.45,.50]    # Chuva
            ])
X0= np.array([[.40],
              [.60]
             ])
# Distribuição para 2020
transicoes = 4
M4 = np.linalg.matrix_power(M,transicoes)
X4 = np.matmul(M4,X0)
print(X4)

[[0.526315]
 [0.473685]]


# 2. Passeios aleatórios num grafo

## 2.1. Passeios aleatórios

- Qual a probabilidade de chegarmos ao nó 3 partindo do nó 1, em exatamente 3 passos?

![passeio_aleatorio_1](imagens/passeio_aleatorio_1.png)

In [27]:
 # Dado:
M= np.array([[0,1/2,0,0,0],
             [0,0,1/3,0,0],
             [1,1/2,0,0,0],
             [0,0,1/3,1,0],
             [0,0,1/3,0,1]
            ])

# Resolução:
# Partindo do nó 1
X0= np.array([[1],[0],[0],[0],[0]])

X3 = np.matmul(np.linalg.matrix_power(M,3),X0)

prob_p3 = np.round(X3[2][0]*100,2)
print(f'Probabilidade de chegar ao nó 3: {prob_p3}%')

Probabilidade de chegar ao nó 3: 16.67%


- E partindo dos nós 4 e 5?

In [28]:
# Comportamento do nó 4 e 5
M1000 = np.linalg.matrix_power(M,1000)
print(np.round(M1000,2))

[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.5 0.5 0.5 1.  0. ]
 [0.5 0.5 0.5 0.  1. ]]


## 2.2. Modelo de transmissão de sinais

- Sabendo que a fiabilidade da linha é p, qual a probabilidade de 0 continuar 0 após dois passos de transmissão?
- Encontre o vetor estacionário para a matriz em questão.
- Considerar p = 0.9

![transmissao_de_sinal1](imagens/transmissao_de_sinal1.png)

In [29]:
# Transmissão de sinal numa linha: 0-1
# Fiabilidade (confiabilidade) da linha
p = 0.9

# Matriz de Markov
#             0 | 1
M= np.array([[p, 1-p], #0
             [1-p, p]  #1
            ])

# Qual a probabilidade de um 0 continuar a ser 0 depois de exatamente 2 passos de transmissão?
X0 = np.array([[1], #0
               [0]  #1
              ])
              
X2 = np.matmul(np.linalg.matrix_power(M,2),X0)

print(f'Vetor para estado 0 após 2 passos:\n{X2}')
print('Probabilidade de:',X2[0][0]*100,'%')

# Vetor estacionário
V_est =np.linalg.matrix_power(M,100)
print(f'Vetor estacionário:\n{V_est}')

Vetor para estado 0 após 2 passos:
[[0.82]
 [0.18]]
Probabilidade de: 82.0 %
Vetor estacionário:
[[0.5 0.5]
 [0.5 0.5]]


- Solução matemática

![solucao_matematica](imagens/solucao_matematica.png)

## 2.3. Passeio num labirinto

- Partindo da sala 1, qual a probabilidade de chegarmos à sala 4 em exatamente três passos?
- E após muitos passos?

![passeio_labirinto](imagens/passeio_labirinto.png)

In [30]:
# Dado:
#              1 |  2|  3|  4| 5
M= np.array([[0.0,1/3,1/4,0.0,0.0], #1
             [1/2,0.0,1/4,1/3,0.0], #2
             [1/2,1/3,0.0,1/3,1/2], #3
             [0.0,1/3,1/4,0.0,1/2], #4
             [0.0,0.0,1/4,1/3,0.0]  #5
            ])
# Em 3 passos:
M3 = np.linalg.matrix_power(M,3)
print(f'Matriz após 4 passos:\n{M3}')
print(f'Probabilidade após 4 passos: {round(M3[3][0]*100,2)}%')

# Após muitos passos
M100 = np.linalg.matrix_power(M,100)
print(f'Matriz após muitos passos:\n{M100}')
print(f'Probabilidade após muitos passos: {round(M100[3][0]*100,2)}%')

Matriz após 4 passos:
[[0.08333333 0.18981481 0.17361111 0.09722222 0.13888889]
 [0.28472222 0.13888889 0.21527778 0.28703704 0.14583333]
 [0.34722222 0.28703704 0.22222222 0.28703704 0.34722222]
 [0.14583333 0.28703704 0.21527778 0.13888889 0.28472222]
 [0.13888889 0.09722222 0.17361111 0.18981481 0.08333333]]
Probabilidade após 4 passos: 14.58%
Matriz após muitos passos:
[[0.14285714 0.14285714 0.14285714 0.14285714 0.14285714]
 [0.21428571 0.21428571 0.21428571 0.21428571 0.21428571]
 [0.28571429 0.28571429 0.28571429 0.28571429 0.28571429]
 [0.21428571 0.21428571 0.21428571 0.21428571 0.21428571]
 [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714]]
Probabilidade após muitos passos: 21.43%


## Exercícios

### 2.1. Matriz do grafo dirigido
- Dado o seguinte grafo orientado com 5 nós, determine a matriz que representa um passeio aleatório simples neste grafo.

![exercicio_2-1](imagens/exercicio_2-1.png)

In [31]:
#              1 |  2|  3|  4| 5
M= np.array([[0.0,0.0,0.0,0.0,0.0], #1
             [1/2,0.0,0.0,0.0,0.0], #2
             [0.0,1.0,0.0,1/2,0.0], #3
             [1/2,0.0,1/2,0.0,0.0], #4
             [0.0,0.0,1/2,1/2,1.0]  #5
            ])
print(M)

[[0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0. ]
 [0.  1.  0.  0.5 0. ]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.  0.5 0.5 1. ]]


### 2.2. Transmissão de sinal
- Dado o modelo de transmissão de sinais ilustrado na figura (cada pedaço de informação é um 0 ou um 1), com p=0.98, calcule a probabilidade do sinal de entrada 1 ser um 0 ao fim de exatamente 3 passos de transmissão.

![exercicio_2-2](imagens/exercicio_2-2.png)

In [32]:
# Transmissão de sinal numa linha: 1-0
# Fiabilidade (confiabilidade) da linha
p = 0.98

# Matriz de Markov
#             0 | 1
M= np.array([[p, 1-p], #0
             [1-p, p]  #1
            ])

passos = 3
M3 = np.linalg.matrix_power(M,passos)
print(M3)
print(f'Probabilidade:{round(M3[1][0]*100,2)}%')

[[0.942368 0.057632]
 [0.057632 0.942368]]
Probabilidade:5.76%


### 3.3. Vetor estacionário
- Indique o vetor estacionário do grafo que se segue.

![exercicio_2-3](imagens/exercicio_2-3.png)

In [33]:
#              1 |  2|  3|  4| 5
M= np.array([[0.0,1/2,1/2,1/3,0.0], #1
             [1/3,0.0,0.0,0.0,1/2], #2
             [1/3,0.0,0.0,1/3,0.0], #3
             [1/3,0.0,1/2,0.0,1/2], #4
             [0.0,1/2,0.0,1/3,0.0]  #5
            ])
print('Matriz de Markov:\n',np.round(M,2))

# Vetor estacionário
M100 = np.linalg.matrix_power(M,100)
V_est= np.matmul(M100,np.array([[1],[0],[0],[0],[0]]))
print('Vetor estacionário:\n',V_est)

Matriz de Markov:
 [[0.   0.5  0.5  0.33 0.  ]
 [0.33 0.   0.   0.   0.5 ]
 [0.33 0.   0.   0.33 0.  ]
 [0.33 0.   0.5  0.   0.5 ]
 [0.   0.5  0.   0.33 0.  ]]
Vetor estacionário:
 [[0.25      ]
 [0.16666666]
 [0.16666667]
 [0.25      ]
 [0.16666667]]


### 3.4. Rato no labirinto
- Assumindo que um rato transita de sala equiprovavelmente a cada contagem do tempo, qual a
probabilidade deste se encontrar na sala 3 após 2 transições, sabendo que partiu da sala 5

![exercicio_2-4](imagens/exercicio_2-4.png)

In [34]:
# Matriz de markov
#              1 |  2|  3|  4| 5
M= np.array([[0.0,1/4,0.0,1/3,0.0], #1
             [1/2,0.0,1/2,1/3,1/3], #2
             [0.0,1/4,0.0,0.0,1/3], #3
             [1/2,1/4,0.0,0.0,1/3], #4
             [0.0,1/4,1/2,1/3,0.0]  #5
            ])
# Após 2 transcições
M2 = np.linalg.matrix_power(M,2)

print(f'Matriz de Markov:\n{np.round(M,2)}\nApós 2 Transações:\n{np.round(M2,2)}')
print(f'Probabilidade:{round(M2[2][4]*100,2)}%')

Matriz de Markov:
[[0.   0.25 0.   0.33 0.  ]
 [0.5  0.   0.5  0.33 0.33]
 [0.   0.25 0.   0.   0.33]
 [0.5  0.25 0.   0.   0.33]
 [0.   0.25 0.5  0.33 0.  ]]
Após 2 Transações:
[[0.29 0.08 0.12 0.08 0.19]
 [0.17 0.42 0.17 0.28 0.28]
 [0.12 0.08 0.29 0.19 0.08]
 [0.12 0.21 0.29 0.36 0.08]
 [0.29 0.21 0.12 0.08 0.36]]
Probabilidade:8.33%


# 3. Passeio aleatório numa rede

## 3.1. WWW com 5 páginas e nós absorventes

- Exemplo de matriz com nó absorvente:

![matriz_no_absorvente](imagens/matriz_no_absorvente.png)

### **Ajuste 1:** 

Substituir colunas associadas aos nós absorventes com entradas iguais para qualquer outro nó disponível na rede.

![matriz_no_absorvente_ajuste_1](imagens/matriz_no_absorvente_ajuste_1.png)

In [35]:
# Matriz de markov com nós absorventes
#              1 |   2|   3|   4|   5
P= np.array([[0.0, 1/2, 0.0, 0.0, 0.0], #1
             [0.0, 0.0, 1/3, 0.0, 0.0], #2
             [1.0, 1/2, 0.0, 0.0, 0.0], #3
             [0.0, 0.0, 1/3, 1.0, 0.0], #4
             [0.0, 0.0, 1/3, 0.0, 1.0]  #5
            ])

# Ajuste 1 
# Em contexto: o websurfer acessará outra página por meio de conhecimentos prévios e não por hiperlink.

P_ajuste1= np.array([[0.0, 1/2, 0.0, 1/5, 1/5], #1
                     [0.0, 0.0, 1/3, 1/5, 1/5], #2
                     [1.0, 1/2, 0.0, 1/5, 1/5], #3
                     [0.0, 0.0, 1/3, 1/5, 1/5], #4
                     [0.0, 0.0, 1/3, 1/5, 1/5]  #5
                    ])

# Verificando regularidade pelo ajuste 1
P_ajuste1_est = np.linalg.matrix_power(P_ajuste1,100)

print(f'Matriz P:\n{np.round(P,2)}\nAjuste 1:\n{np.round(P_ajuste1,2)}\nVerificando regularidade do ajuste 1:\n{np.round(P_ajuste1_est,2)}')

Matriz P:
[[0.   0.5  0.   0.   0.  ]
 [0.   0.   0.33 0.   0.  ]
 [1.   0.5  0.   0.   0.  ]
 [0.   0.   0.33 1.   0.  ]
 [0.   0.   0.33 0.   1.  ]]
Ajuste 1:
[[0.   0.5  0.   0.2  0.2 ]
 [0.   0.   0.33 0.2  0.2 ]
 [1.   0.5  0.   0.2  0.2 ]
 [0.   0.   0.33 0.2  0.2 ]
 [0.   0.   0.33 0.2  0.2 ]]
Verificando regularidade do ajuste 1:
[[0.16 0.16 0.16 0.16 0.16]
 [0.18 0.18 0.18 0.18 0.18]
 [0.32 0.32 0.32 0.32 0.32]
 [0.18 0.18 0.18 0.18 0.18]
 [0.18 0.18 0.18 0.18 0.18]]


## Exercicios

### 3.1. Redes sociais
- Considere uma rede social com 7 participantes cujas páginas têm ligações representadas por setas no seguinte grafo.
- Determine a probabilidade do participante A desta rede visitar o participante B após um passeio aleatório por todas as páginas da rede em 4 visitas.

![exercicio_3-1](imagens/exercicio_3-1.png)

In [36]:
#               A|   B|   C|   D|   E|   F|   G
P= np.array([[0.0, 1/6, 1/7, 1/4, 1/7, 0.0, 1/7], #A
             [1/6, 0.0, 1/7, 1/4, 1/7, 0.0, 1/7], #B
             [1/6, 1/6, 1/7, 0.0, 1/7, 0.0, 1/7], #C
             [1/6, 1/6, 1/7, 0.0, 1/7, 1.0, 1/7], #D
             [1/6, 1/6, 1/7, 1/4, 1/7, 0.0, 1/7], #E
             [1/6, 1/6, 1/7, 0.0, 1/7, 0.0, 1/7], #F
             [1/6, 1/6, 1/7, 1/4, 1/7, 0.0, 1/7]  #G
            ])

# Após 4 visitas
P4 = np.linalg.matrix_power(P,4)

print(np.round(P4,4))
print(f'Probabilidade:{round(P4[1][0]*100,2)}%')

[[0.1335 0.1327 0.1344 0.141  0.1344 0.1239 0.1344]
 [0.1327 0.1335 0.1344 0.141  0.1344 0.1239 0.1344]
 [0.1078 0.1078 0.1062 0.0969 0.1062 0.104  0.1062]
 [0.2046 0.2046 0.2033 0.201  0.2033 0.2588 0.2033]
 [0.1568 0.1568 0.1577 0.1616 0.1577 0.1427 0.1577]
 [0.1078 0.1078 0.1062 0.0969 0.1062 0.104  0.1062]
 [0.1568 0.1568 0.1577 0.1616 0.1577 0.1427 0.1577]]
Probabilidade:13.27%


### Ajuste 1 do PageRank

- Considere uma rede com 6 páginas web e com hiperligações representadas por setas no seguinte grafo.
- Determine a fração de tempo que o web surfer vai passar em cada uma das páginas.

![exercicio_3-2](imagens/exercicio_3-2.png)

In [37]:
#              1 |   2|   3|   4|   5|   6
P= np.array([[0.0, 1/4, 1/6, 1/3, 1/3, 1/6], #1
             [1/3, 0.0, 1/6, 1/3, 1/3, 1/6], #2
             [1/3, 1/4, 1/6, 0.0, 0.0, 1/6], #3
             [0.0, 1/4, 1/6, 0.0, 1/3, 1/6], #4
             [1/3, 0.0, 1/6, 1/3, 0.0, 1/6], #5
             [0.0, 1/4, 1/6, 0.0, 0.0, 1/6]  #6
            ])

print(f'Matriz de Markov:\n{np.round(P,3)}')

# Matriz estacionária
P_est = np.linalg.matrix_power(P,100)

print(f'Matriz Estacionária:\n{np.round(P_est,3)}')

Matriz de Markov:
[[0.    0.25  0.167 0.333 0.333 0.167]
 [0.333 0.    0.167 0.333 0.333 0.167]
 [0.333 0.25  0.167 0.    0.    0.167]
 [0.    0.25  0.167 0.    0.333 0.167]
 [0.333 0.    0.167 0.333 0.    0.167]
 [0.    0.25  0.167 0.    0.    0.167]]
Matriz Estacionária:
[[0.203 0.203 0.203 0.203 0.203 0.203]
 [0.217 0.217 0.217 0.217 0.217 0.217]
 [0.166 0.166 0.166 0.166 0.166 0.166]
 [0.153 0.153 0.153 0.153 0.153 0.153]
 [0.163 0.163 0.163 0.163 0.163 0.163]
 [0.098 0.098 0.098 0.098 0.098 0.098]]


# 4. Google PageRank

## 4.1. Ciclos na rede

### **Aplicação do Ajuste 2 - Clusters não conectados**

![www_8_paginas_2_clusters](imagens/www_8_paginas_2_clusters.png)

### **Ajuste 2**

Ajustar o nó absorvente como já foi explicado (ajuste 1) e somar algebricamente por uma matriz (K) de probabilidades iguais para cada linha e coluna.

A matriz P terá peso 0.85 e a matriz K, 0.15 (Parâmetros usados pela Google)

In [38]:
# Rede com dois clusters não conectados
# 5+3 páginas e um nó absorvente

#               1|   2|   3|   4|   5|   6|   7|   8
P= np.array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], #1
             [1/3, 0.0, 0.0, 0.0, 1/2, 0.0, 0.0, 0.0], #2
             [1/3, 1/2, 1.0, 1/2, 0.0, 0.0, 0.0, 0.0], #3
             [0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 0.0, 0.0], #4
             [1/3, 1/2, 0.0, 1/2, 0.0, 0.0, 0.0, 0.0], #5
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0], #6
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 1.0], #7
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 1/2, 0.0]  #8
            ])

# Vale lembrar que a parte ajustada deve ser referente somente ao cluster que contém o nó absorvente, nesse caso, o bloco P11
#                      1|   2|   3|   4|   5|   6|   7|   8
P_ajuste= np.array([[0.0, 0.0, 1/5, 0.0, 0.0, 0.0, 0.0, 0.0], #1
                    [1/3, 0.0, 1/5, 0.0, 1/2, 0.0, 0.0, 0.0], #2
                    [1/3, 1/2, 1/5, 1/2, 0.0, 0.0, 0.0, 0.0], #3
                    [0.0, 0.0, 1/5, 0.0, 1/2, 0.0, 0.0, 0.0], #4
                    [1/3, 1/2, 1/5, 1/2, 0.0, 0.0, 0.0, 0.0], #5
                    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0], #6
                    [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 1.0], #7
                    [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 1/2, 0.0]  #8
                   ])

#               1|   2|   3|   4|   5|   6|   7|   8
K= np.array([[1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #1
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #2
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #3
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #4
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #5
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #6
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #7
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8]  #8
            ])

# Realizando o ajuste
p=0.85 #Probabilidade do web surfer seguir hiperlinks (visitar outras páginas)
G = p*P_ajuste+(1-p)*K
print(f'Matriz ajustada:\n{np.round(G,4)}')

# Matriz estacionária pós ajuste
G100 = np.linalg.matrix_power(G,100)

print(f'Matriz estacionária pós ajuste:\n{np.round(G100,4)}')

Matriz ajustada:
[[0.0188 0.0188 0.1888 0.0188 0.0188 0.0188 0.0188 0.0188]
 [0.3021 0.0188 0.1888 0.0188 0.4438 0.0188 0.0188 0.0188]
 [0.3021 0.4438 0.1888 0.4438 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.0188 0.1888 0.0188 0.4438 0.0188 0.0188 0.0188]
 [0.3021 0.4438 0.1888 0.4438 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.0188 0.4438 0.0188]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.4438 0.0188 0.8688]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.4438 0.4438 0.0188]]
Matriz estacionária pós ajuste:
[[0.0469 0.0469 0.0469 0.0469 0.0469 0.0469 0.0469 0.0469]
 [0.1304 0.1304 0.1304 0.1304 0.1304 0.1304 0.1304 0.1304]
 [0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653]
 [0.1171 0.1171 0.1171 0.1171 0.1171 0.1171 0.1171 0.1171]
 [0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653]
 [0.0877 0.0877 0.0877 0.0877 0.0877 0.0877 0.0877 0.0877]
 [0.1623 0.1623 0.1623 0.1623 0.1623 0.1623 0.1623 0.1623]
 [0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125 ]]


## Exercícios

### 4.1. Page ranking

- Considere uma rede com 7 páginas e com hiperligações representadas por setas no seguinte grafo. 
- Faça o ajuste necessário e determine a página (ou páginas em simultâneo) que têm o ranking mais elevado desta rede.

![exercicio_4-1](imagens/exercicio_4-1.png)

In [39]:
# Matriz de Markov Ajustada (ajuste 1)
#               1|   2|   3|   4|   5|   6|   7|
P= np.array([[0.0, 1/2, 0.0, 1/2, 1/2, 1/3, 1/7], #1
             [0.0, 0.0, 0.0, 1/2, 0.0, 1/3, 1/7], #2
             [0.0, 0.0, 0.0, 0.0, 1/2, 1/3, 1/7], #3
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1/7], #4
             [0.0, 0.0, 1/2, 0.0, 0.0, 0.0, 1/7], #5
             [1.0, 0.0, 1/2, 0.0, 0.0, 0.0, 1/7], #6
             [0.0, 1/2, 0.0, 0.0, 0.0, 0.0, 1/7], #7
            ])
P100 = np.linalg.matrix_power(P,100)
print(np.round(P100,4))
# R: Página 6

[[0.2273 0.2273 0.2273 0.2273 0.2273 0.2273 0.2273]
 [0.1212 0.1212 0.1212 0.1212 0.1212 0.1212 0.1212]
 [0.1616 0.1616 0.1616 0.1616 0.1616 0.1616 0.1616]
 [0.0101 0.0101 0.0101 0.0101 0.0101 0.0101 0.0101]
 [0.0909 0.0909 0.0909 0.0909 0.0909 0.0909 0.0909]
 [0.3182 0.3182 0.3182 0.3182 0.3182 0.3182 0.3182]
 [0.0707 0.0707 0.0707 0.0707 0.0707 0.0707 0.0707]]


### 4.2. Google Matrix

- Faça os ajustes necessários da matriz para determinar as entradas 1, 4, 5 e 7 do (único) vetor estacionário para a rede WWW da figura.

![exercicio_4-2](imagens/exercicio_4-2.png)

In [43]:
#               1|   2|   3|   4|   5|   6|   7|   8
P= np.array([[0.0, 0.0, 1/2, 1/4, 0.0, 0.0, 0.0, 0.0], #1
             [1/2, 0.0, 1/2, 1/4, 0.0, 0.0, 0.0, 0.0], #2
             [1/2, 1/2, 0.0, 1/4, 0.0, 0.0, 0.0, 0.0], #3
             [0.0, 1/2, 0.0, 1/4, 0.0, 0.0, 0.0, 0.0], #4
#----------------------------------------------------Separando clusters
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/3, 1.0, 1/4], #5
             [0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 0.0, 1/4], #6
             [0.0, 0.0, 0.0, 0.0, 1/2, 1/3, 0.0, 1/4], #7
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/3, 0.0, 1/4]  #8
            ])
#               1|   2|   3|   4|   5|   6|   7|   8
K= np.array([[1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #1
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #2
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #3
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #4
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #5
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #6
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #7
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8]  #8
            ])

# Realizando o ajuste
p=0.85
G = p*P+(1-p)*K
print(f'Matriz ajustada:\n{np.round(G,4)}')

# Matriz estacionária pós ajuste
G100 = np.linalg.matrix_power(G,10000)
print(f'Matriz estacionária:\n{np.round(G100,4)}')

Matriz ajustada:
[[0.0188 0.0188 0.4438 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.4438 0.0188 0.4438 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.4438 0.4438 0.0188 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.4438 0.0188 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.3021 0.8688 0.2312]
 [0.0188 0.0188 0.0188 0.0188 0.4438 0.0188 0.0188 0.2312]
 [0.0188 0.0188 0.0188 0.0188 0.4438 0.3021 0.0188 0.2312]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.3021 0.0188 0.2312]]
Matriz estacionária:
[[0.1031 0.1031 0.1031 0.1031 0.1031 0.1031 0.1031 0.1031]
 [0.1469 0.1469 0.1469 0.1469 0.1469 0.1469 0.1469 0.1469]
 [0.1469 0.1469 0.1469 0.1469 0.1469 0.1469 0.1469 0.1469]
 [0.1031 0.1031 0.1031 0.1031 0.1031 0.1031 0.1031 0.1031]
 [0.1841 0.1841 0.1841 0.1841 0.1841 0.1841 0.1841 0.1841]
 [0.1105 0.1105 0.1105 0.1105 0.1105 0.1105 0.1105 0.1105]
 [0.1418 0.1418 0.1418 0.1418 0.1418 0.1418 0.1418 0.1418]
 [0.0636 0.0636 0.0636 0.0636 0.0636 0.0636 0.0636 0.0636]]
