In [2]:
import numpy as np

# Cadeias de Markov
São modelos matemáticos que descrevem a evolução de um sistema que passa sucessivamente por diferentes estados, onde cada estado seguinte é dependente do anterior imediato.

# 1. Prever o longo prazo / Predicte the long-run

## 1.1. Modelo cássico: 2 estados

### **Previsão do Tempo**

- Sabendo que hoje está sol, o que devemos esperar daqui a dois dias?

![Modelo Cálssico](imagens/modelo_classico_2_estados.png)

In [3]:
# Matriz transição
M = np.array([[0.5, 0.3],
              [0.5, 0.7]]
            )
            
# Estado inicial
X0 = np.array([[1],[0]])

# 1 dia após
X1 = np.matmul(M,X0)
# 2 dias após
X2 = np.matmul(M,X1)

# 2 dias após pode ser calculado da forma
dias = 2
M_intermed = np.linalg.matrix_power(M,dias)
X2 = np.matmul(M_intermed,X0)

# Após 1 ano:
dias = 365
M_intermed = np.linalg.matrix_power(M,dias)
X1a = np.matmul(M_intermed,X0)

print(f'Matriz transição:\n{M}\nEstado inicial:\n{X0}\nApós 1 dia:\n{X1}\nApós 2 dias:\n{X2}\nApós 1 ano:\n{X1a}')

Matriz transição:
[[0.5 0.3]
 [0.5 0.7]]
Estado inicial:
[[1]
 [0]]
Após 1 dia:
[[0.5]
 [0.5]]
Após 2 dias:
[[0.4]
 [0.6]]
Após 1 ano:
[[0.375]
 [0.625]]


#### Conclusões
- Generalização do modelo: $$ X_k+_1 = MX_k $$
- Vetor estacionário (c1) $$ Lim (k > inf) M^k = c_1 $$
- Dias com nuvem após dias de sol são muito mais frequentes

### **Previsão de mobilidade**

- Sabendo que a distribuição da população em 2010 é: 5x10^6 na cidade e 1x10^6 nos arredores, qual será a distribuição em 2020?
- Matriz de transição =  matriz de mobilidade de 5 em 5 anos

![Alt text](imagens/modelo_classico_2_estados_distribuicao_pop.png)

In [4]:
# Matriz de mobilidade da população em 5 em 5 anos
M = np.array([[.7,.5],
              [.3,.5]]
            )

# Estados inicial
X0 = np.array([[5E6],
              [1E6]]
             )

# Distribuição em 2020:
# 10 anos de diferença = 2 passos de 5, logo:
X2 = np.matmul((np.linalg.matrix_power(M,2)),X0)
print(f'Após 10 anos:\n{X2}')

# Qual será a distribuição daqui a 100 anos? 
passo = int(100/5)
X100 = np.matmul((np.linalg.matrix_power(M,passo)),X0)
print(f'Após 100 anos:\n{X100}')

Após 10 anos:
[[3800000.]
 [2200000.]]
Após 100 anos:
[[3750000.00000001]
 [2249999.99999999]]


In [5]:
M= np.array([[3,-4,-1,-3,2],
             [-2,0,-4,2,3],
             [-1,0,-4,-2,2],
             [-1,2,0,-4,4],
             [-4,-3,-4,1,-4]
            ])
np.linalg.matrix_power(M,5)

array([[  4699,   -984,  10137,    415,  -6750],
       [ -1018,   3076,   5633,   2363,  -3249],
       [  2887,   5474,  13771,    919,  -4140],
       [ -1401,    608,  10333,   6643, -11830],
       [  6514,  12419,  11290,  -7847,  11502]])

## 1.2. Modelo de 3 estados

### **Distribuição de bicicletas entre prédios da universidade**

- Dada matriz de transição, e, sabendo que 300 bicicletas serão distribuídas segundo matriz de estado inicial, avalie a distribuição das bicicletas a longo prazo.

![Alt text](imagens/modelo_3_estados_distrib_bikes.png)

In [6]:
# Distribuição de bicicletas entre os prédios da universidade
M = np.array([[.95,.02,.05],
              [.03,.9,.05],
              [.02,.08,.9]
             ])
# 300 Bicicletas distribuídas na 2ª feira nas seguintes frações:
X0 = np.array([[.5],
               [.3],
               [.2]
              ])
# Distribuição na segunda (para comparação)
print('Distribuição na segunda feira:','\n',X0*300)

# Distribuição na quinta feira
passo = 3
X3 = np.matmul((np.linalg.matrix_power(M,passo)),X0)
# Necessário multiplicar pelas 300 bicicletas disponíveis para encontrar a distribuição real
X3 = X3*300
print('Distribuição na quinta feira:','\n',X3)

# Obtendo a distribuição estável a longo prazo
passo = 100
X_longo = np.matmul((np.linalg.matrix_power(M,passo)),X0)
# Multiplicar pelas 300 bicicletas disponíveis
X_longo = X_longo*300
print('Distribuição a longo prazo:','\n',X_longo)

Distribuição na segunda feira: 
 [[150.]
 [ 90.]
 [ 60.]]
Distribuição na quinta feira: 
 [[142.80513]
 [ 86.28885]
 [ 70.90602]]
Distribuição a longo prazo: 
 [[125.00148948]
 [ 83.33283724]
 [ 91.66567328]]


## Exercícios

### 1.1 Previsão de estado

![Alt text](imagens/exercicio_1-1_previsao_de_estado.png)

In [7]:
# Questão 1 - Previsão de estado
#Um dado processo de Markov com dois estados encontra-se inicialmente no estado 1 e sabe-se que a matriz de transição da cadeia é dada por:
M = np.array([[1/2,9/14],
              [1/2,5/14]
             ])
X0 = np.array([[1],
               [0]
              ])
# Qual a probabilidade da cadeia se encontrar no estado 2 decorridas exatamente 4 transições?
transicoes = 4
M4 = np.linalg.matrix_power(M,transicoes)
X4 = np.matmul(M4,X0)
print(X4)

[[0.56268222]
 [0.43731778]]


### 1.2. Matriz de transição

![Alt text](imagens/exercicio_1-2.png)

In [8]:
# Questão 2 - Matriz de transição
# Num dado país, as votações estão há vários anos bipolarizadas em dois partidos políticos, o PDC e o BEL. De 4 em 4 anos, a percentagem de votantes no PDC que continua a votar em PDC é de 55%, enquanto 45% dos anteriores votos no PCD passam para o BEL. Por outro lado, nesse mesmo período, há 50% de votos no BEL que são deslocados para votos no PDC e os restantes 50% permanecem votos no BEL.

# Qual a matriz de transição do voto eleitoral no país em causa?
M = np.array([[.55,.50],
              [.45,.50]
             ])
print(M)

[[0.55 0.5 ]
 [0.45 0.5 ]]


### 1.3. Previsão de tempo

![Alt text](imagens/exercicio_1-3.png)

In [9]:
# Questão 3 - Previsão de tempo
# Numa dada região, o clima alterna anualmente de acordo com o seguinte modelo. Cada ano, a probabilidade de vir um ano seco a seguir a um ano sem chuva é de 55%, e a de vir um ano de chuvas a seguir a um ano seco é de 45%. Por outro lado, anualmente, há 50% de probabilidade de a seguir a um ano de chuvas vir um ano de seca e 50% de vir um ano de chuvas após um ano de chuvas.

# Suponha que a previsão para 2016 era de 40% de ano seco e de 60% de chuvas fortes.

# Qual a distribuição de previsão do tempo para 2020?
#             Seco|Chuva
M= np.array([[1-.45,.50], # Seco
             [.45,.50]    # Chuva
            ])
X0= np.array([[.40],
              [.60]
             ])
# Distribuição para 2020
transicoes = 4
M4 = np.linalg.matrix_power(M,transicoes)
X4 = np.matmul(M4,X0)
print(X4)

[[0.526315]
 [0.473685]]


# 2. Passeios aleatórios num grafo

## 2.1. Passeios aleatórios

- Qual a probabilidade de chegarmos ao nó 3 partindo do nó 1, em exatamente 3 passos?

![Alt text](imagens/passeio_aleatorio_1.png)

In [20]:
 # Dado:
M= np.array([[0,1/2,0,0,0],
             [0,0,1/3,0,0],
             [1,1/2,0,0,0],
             [0,0,1/3,1,0],
             [0,0,1/3,0,1]
            ])

# Resolução:
# Partindo do nó 1
X0= np.array([[1],[0],[0],[0],[0]])

X3 = np.matmul(np.linalg.matrix_power(M,3),X0)

prob_p3 = np.round(X3[2][0]*100,2)
print(f'Probabilidade de chegar ao nó 3: {prob_p3}%')

Probabilidade de chegar ao nó 3: 16.67%


- E partindo dos nós 4 e 5?

In [21]:
# Comportamento do nó 4 e 5
M1000 = np.linalg.matrix_power(M,1000)
print(np.round(M1000,2))

[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.5 0.5 0.5 1.  0. ]
 [0.5 0.5 0.5 0.  1. ]]


## 2.2. Modelo de transmissão de sinais

In [13]:
# Transmissão de sinal numa linha: 0-1
# Fiabilidade (confiabilidade) da linha
p = 0.9

# Matriz de Markov
#             0 | 1
M= np.array([[p, 1-p], #0
             [1-p, p]  #1
            ])

# Qual a probabilidade de um 0 continuar a ser 0 depois de exatamente 2 passos de transmissão?
X0 = np.array([[1], #0
               [0]  #1
              ])
X2 = np.matmul(np.linalg.matrix_power(M,2),X0)
print(X2)
print('Probabilidade de:',X2[0][0]*100,'%')

# Vetor estacionário
V_est =np.linalg.matrix_power(M,100)
print(V_est)

[[0.82]
 [0.18]]
Probabilidade de: 82.0 %
[[0.5 0.5]
 [0.5 0.5]]


## 2.3 - Rato num labirinto

In [14]:
# Partindo da sala 1, qual a probabilidade de chegarmos à sala 4 em exatamente três passos?
# Dado:
#              1 |  2|  3|  4| 5
M= np.array([[0.0,1/3,1/4,0.0,0.0], #1
             [1/2,0.0,1/4,1/3,0.0], #2
             [1/2,1/3,0.0,1/3,1/2], #3
             [0.0,1/3,1/4,0.0,1/2], #4
             [0.0,0.0,1/4,1/3,0.0]  #5
            ])
# Em 3 passos:
M3 = np.linalg.matrix_power(M,3)
# print(M3)
# print(f'Probabilidade:{round(M3[3][0]*100,2)}%')

# Após muitos passos
M100 = np.linalg.matrix_power(M,100)
print(M100)
print(f'Probabilidade:{round(M100[3][0]*100,2)}%')

[[0.14285714 0.14285714 0.14285714 0.14285714 0.14285714]
 [0.21428571 0.21428571 0.21428571 0.21428571 0.21428571]
 [0.28571429 0.28571429 0.28571429 0.28571429 0.28571429]
 [0.21428571 0.21428571 0.21428571 0.21428571 0.21428571]
 [0.14285714 0.14285714 0.14285714 0.14285714 0.14285714]]
Probabilidade:21.43%


## Teste 2

In [15]:
# Questão 1
# Dado o seguinte grafo orientado com 5 nós, determine a matriz que representa um passeio aleatório simples neste grafo.

#              1 |  2|  3|  4| 5
M= np.array([[0.0,0.0,0.0,0.0,0.0], #1
             [1/2,0.0,0.0,0.0,0.0], #2
             [0.0,1.0,0.0,1/2,0.0], #3
             [1/2,0.0,1/2,0.0,0.0], #4
             [0.0,0.0,1/2,1/2,1.0]  #5
            ])
print(M)

[[0.  0.  0.  0.  0. ]
 [0.5 0.  0.  0.  0. ]
 [0.  1.  0.  0.5 0. ]
 [0.5 0.  0.5 0.  0. ]
 [0.  0.  0.5 0.5 1. ]]


In [16]:
# Questão 2
# Dado o modelo de transmissão de sinais ilustrado na figura (cada pedaço de informação é um 0 ou um 1), com p=0.98, calcule a probabilidade do sinal de entrada 1 ser um 0 ao fim de exatamente 3 passos de transmissão.

# Transmissão de sinal numa linha: 1-0
# Fiabilidade (confiabilidade) da linha
p = 0.98

# Matriz de Markov
#             0 | 1
M= np.array([[p, 1-p], #0
             [1-p, p]  #1
            ])

passos = 3
M3 = np.linalg.matrix_power(M,passos)
print(M3)
print(f'Probabilidade:{round(M3[1][0]*100,2)}%')

[[0.942368 0.057632]
 [0.057632 0.942368]]
Probabilidade:5.76%


In [17]:
# Questão 3
# Indique o vetor estacionário do grafo que se segue, sabendo que é da forma
#              1 |  2|  3|  4| 5
M= np.array([[0.0,1/2,1/2,1/3,0.0], #1
             [1/3,0.0,0.0,0.0,1/2], #2
             [1/3,0.0,0.0,1/3,0.0], #3
             [1/3,0.0,1/2,0.0,1/2], #4
             [0.0,1/2,0.0,1/3,0.0]  #5
            ])
print('Matriz de Markov:\n',np.round(M,2))

# Vetor estacionário
M100 = np.linalg.matrix_power(M,100)
V_est= np.matmul(M100,np.array([[1],[0],[0],[0],[0]]))
print('Vetor estacionário:\n',V_est)

Matriz de Markov:
 [[0.   0.5  0.5  0.33 0.  ]
 [0.33 0.   0.   0.   0.5 ]
 [0.33 0.   0.   0.33 0.  ]
 [0.33 0.   0.5  0.   0.5 ]
 [0.   0.5  0.   0.33 0.  ]]
Vetor estacionário:
 [[0.25      ]
 [0.16666666]
 [0.16666667]
 [0.25      ]
 [0.16666667]]


In [18]:
# Questão 4
# Considere o labirinto com 5 salas da figura.
# Assumindo que um rato transita de sala equiprovavelmente a cada contagem do tempo, qual a probabilidade deste se encontrar na sala 3 após 2 transições, sabendo que partiu da sala 5

# Matriz de markov
#              1 |  2|  3|  4| 5
M= np.array([[0.0,1/4,0.0,1/3,0.0], #1
             [1/2,0.0,1/2,1/3,1/3], #2
             [0.0,1/4,0.0,0.0,1/3], #3
             [1/2,1/4,0.0,0.0,1/3], #4
             [0.0,1/4,1/2,1/3,0.0]  #5
            ])
# Após 2 transcições
M2 = np.linalg.matrix_power(M,2)

print(f'Matriz de Markov:\n{np.round(M,2)}\nApós 2 Transações:\n{np.round(M2,2)}')
print(f'Probabilidade:{round(M2[2][4]*100,2)}%')

Matriz de Markov:
[[0.   0.25 0.   0.33 0.  ]
 [0.5  0.   0.5  0.33 0.33]
 [0.   0.25 0.   0.   0.33]
 [0.5  0.25 0.   0.   0.33]
 [0.   0.25 0.5  0.33 0.  ]]
Após 2 Transações:
[[0.29 0.08 0.12 0.08 0.19]
 [0.17 0.42 0.17 0.28 0.28]
 [0.12 0.08 0.29 0.19 0.08]
 [0.12 0.21 0.29 0.36 0.08]
 [0.29 0.21 0.12 0.08 0.36]]
Probabilidade:8.33%


# 3 - Passeio aleatório numa rede/ Random walk in a web

## 3.1 - WWW com 5 páginas e nós absorventes

In [19]:
# Matriz de markov com nós absorventes
#              1 |   2|   3|   4|   5
P= np.array([[0.0, 1/2, 0.0, 0.0, 0.0], #1
             [0.0, 0.0, 1/3, 0.0, 0.0], #2
             [1.0, 1/2, 0.0, 0.0, 0.0], #3
             [0.0, 0.0, 1/3, 1.0, 0.0], #4
             [0.0, 0.0, 1/3, 0.0, 1.0]  #5
            ])

# Ajuste 1:Substituir colunas associadas aos nós absorventes com entradas iguais para qualquer outro nó disponível na rede. 
# Em contexto: o websurfer acessará outra página por meio de conhecimentos prévios e não por hiperlink.

P_ajuste1= np.array([[0.0, 1/2, 0.0, 1/5, 1/5], #1
                     [0.0, 0.0, 1/3, 1/5, 1/5], #2
                     [1.0, 1/2, 0.0, 1/5, 1/5], #3
                     [0.0, 0.0, 1/3, 1/5, 1/5], #4
                     [0.0, 0.0, 1/3, 1/5, 1/5]  #5
                    ])

# Verificando regularidade pelo ajuste 1
P_ajuste1_est = np.linalg.matrix_power(P_ajuste1,100)

print(f'Matriz P:\n{np.round(P,2)}\nAjuste 1:\n{np.round(P_ajuste1,2)}\nVerificando regularidade do ajuste 1:\n{np.round(P_ajuste1_est,2)}')

Matriz P:
[[0.   0.5  0.   0.   0.  ]
 [0.   0.   0.33 0.   0.  ]
 [1.   0.5  0.   0.   0.  ]
 [0.   0.   0.33 1.   0.  ]
 [0.   0.   0.33 0.   1.  ]]
Ajuste 1:
[[0.   0.5  0.   0.2  0.2 ]
 [0.   0.   0.33 0.2  0.2 ]
 [1.   0.5  0.   0.2  0.2 ]
 [0.   0.   0.33 0.2  0.2 ]
 [0.   0.   0.33 0.2  0.2 ]]
Verificando regularidade do ajuste 1:
[[0.16 0.16 0.16 0.16 0.16]
 [0.18 0.18 0.18 0.18 0.18]
 [0.32 0.32 0.32 0.32 0.32]
 [0.18 0.18 0.18 0.18 0.18]
 [0.18 0.18 0.18 0.18 0.18]]


## 3.2 - WWW com 6 páginas e um nó absorvente

In [20]:
# Matriz de markov com nós absorventes
#              1 |   2|   3|   4|   5|   6
P= np.array([[0.0, 1/2, 0.0, 0.0, 0.0, 0.0], #1
             [0.0, 0.0, 1/3, 0.0, 1/2, 0.0], #2
             [1.0, 0.0, 0.0, 0.0, 0.0, 1/2], #3
             [0.0, 0.0, 1/3, 1.0, 0.0, 0.0], #4
             [0.0, 1/2, 0.0, 0.0, 0.0, 1/2], #5
             [0.0, 0.0, 1/3, 0.0, 1/2, 0.0]  #6
            ])
# Matriz estacionária
P_est = np.linalg.matrix_power(P,100)
# Ajustando
#                     1 |   2|   3|   4|   5|   6
P_ajuste= np.array([[0.0, 1/2, 0.0, 1/6, 0.0, 0.0], #1
                    [0.0, 0.0, 1/3, 1/6, 1/2, 0.0], #2
                    [1.0, 0.0, 0.0, 1/6, 0.0, 1/2], #3
                    [0.0, 0.0, 1/3, 1/6, 0.0, 0.0], #4
                    [0.0, 1/2, 0.0, 1/6, 0.0, 1/2], #5
                    [0.0, 0.0, 1/3, 1/6, 1/2, 0.0]  #6
                   ])

P_ajuste_est = np.linalg.matrix_power(P_ajuste,100)

print(f'Matriz P:\n{np.round(P,3)}\nVerificando regularidade da matriz P:\n{np.round(P_est,3)}\nAjuste:\n{np.round(P_ajuste,3)}\nVerificando regularidade do ajuste:\n{np.round(P_ajuste_est,3)}')

Matriz P:
[[0.    0.5   0.    0.    0.    0.   ]
 [0.    0.    0.333 0.    0.5   0.   ]
 [1.    0.    0.    0.    0.    0.5  ]
 [0.    0.    0.333 1.    0.    0.   ]
 [0.    0.5   0.    0.    0.    0.5  ]
 [0.    0.    0.333 0.    0.5   0.   ]]
Verificando regularidade da matriz P:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Ajuste:
[[0.    0.5   0.    0.167 0.    0.   ]
 [0.    0.    0.333 0.167 0.5   0.   ]
 [1.    0.    0.    0.167 0.    0.5  ]
 [0.    0.    0.333 0.167 0.    0.   ]
 [0.    0.5   0.    0.167 0.    0.5  ]
 [0.    0.    0.333 0.167 0.5   0.   ]]
Verificando regularidade do ajuste:
[[0.109 0.109 0.109 0.109 0.109 0.109]
 [0.19  0.19  0.19  0.19  0.19  0.19 ]
 [0.219 0.219 0.219 0.219 0.219 0.219]
 [0.088 0.088 0.088 0.088 0.088 0.088]
 [0.204 0.204 0.204 0.204 0.204 0.204]
 [0.19  0.19  0.19  0.19  0.19  0.19 ]]


## Teste 3

In [21]:
# Questão 1
# Considere uma rede social com 7 participantes cujas páginas têm ligações representadas por setas no seguinte grafo.
# Determine a probabilidade do participante A desta rede visitar o participante B após um passeio aleatório por todas as páginas da rede em 4 visitas.

#               A|   B|   C|   D|   E|   F|   G
P= np.array([[0.0, 1/6, 1/7, 1/4, 1/7, 0.0, 1/7], #A
             [1/6, 0.0, 1/7, 1/4, 1/7, 0.0, 1/7], #B
             [1/6, 1/6, 1/7, 0.0, 1/7, 0.0, 1/7], #C
             [1/6, 1/6, 1/7, 0.0, 1/7, 1.0, 1/7], #D
             [1/6, 1/6, 1/7, 1/4, 1/7, 0.0, 1/7], #E
             [1/6, 1/6, 1/7, 0.0, 1/7, 0.0, 1/7], #F
             [1/6, 1/6, 1/7, 1/4, 1/7, 0.0, 1/7]  #G
            ])

# Após 4 visitas
P4 = np.linalg.matrix_power(P,4)

print(np.round(P4,4))
print(f'Probabilidade:{round(P4[1][0]*100,2)}%')

[[0.1335 0.1327 0.1344 0.141  0.1344 0.1239 0.1344]
 [0.1327 0.1335 0.1344 0.141  0.1344 0.1239 0.1344]
 [0.1078 0.1078 0.1062 0.0969 0.1062 0.104  0.1062]
 [0.2046 0.2046 0.2033 0.201  0.2033 0.2588 0.2033]
 [0.1568 0.1568 0.1577 0.1616 0.1577 0.1427 0.1577]
 [0.1078 0.1078 0.1062 0.0969 0.1062 0.104  0.1062]
 [0.1568 0.1568 0.1577 0.1616 0.1577 0.1427 0.1577]]
Probabilidade:13.27%


In [22]:
# Questão 3
# Considere uma rede com 6 páginas web e com hiperligações representadas por setas no seguinte grafo.
# Determine a fração de tempo que o web surfer vai passar em cada uma das páginas.

#              1 |   2|   3|   4|   5|   6
P= np.array([[0.0, 1/4, 1/6, 1/3, 1/3, 1/6], #1
             [1/3, 0.0, 1/6, 1/3, 1/3, 1/6], #2
             [1/3, 1/4, 1/6, 0.0, 0.0, 1/6], #3
             [0.0, 1/4, 1/6, 0.0, 1/3, 1/6], #4
             [1/3, 0.0, 1/6, 1/3, 0.0, 1/6], #5
             [0.0, 1/4, 1/6, 0.0, 0.0, 1/6]  #6
            ])

print(f'Matriz de Markov:\n{np.round(P,3)}')

# Matriz estacionária
P_est = np.linalg.matrix_power(P,100)

print(f'Matriz Estacionária:\n{np.round(P_est,3)}')

Matriz de Markov:
[[0.    0.25  0.167 0.333 0.333 0.167]
 [0.333 0.    0.167 0.333 0.333 0.167]
 [0.333 0.25  0.167 0.    0.    0.167]
 [0.    0.25  0.167 0.    0.333 0.167]
 [0.333 0.    0.167 0.333 0.    0.167]
 [0.    0.25  0.167 0.    0.    0.167]]
Matriz Estacionária:
[[0.203 0.203 0.203 0.203 0.203 0.203]
 [0.217 0.217 0.217 0.217 0.217 0.217]
 [0.166 0.166 0.166 0.166 0.166 0.166]
 [0.153 0.153 0.153 0.153 0.153 0.153]
 [0.163 0.163 0.163 0.163 0.163 0.163]
 [0.098 0.098 0.098 0.098 0.098 0.098]]


# 4 - Google PageRank

## 4.1 - Ciclos na rede

## Aplicação do Ajuste 2

In [23]:
# Rede com dois clusters não conectados
# 5+3 páginas e um nó absorvente

#               1|   2|   3|   4|   5|   6|   7|   8
P= np.array([[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], #1
             [1/3, 0.0, 0.0, 0.0, 1/2, 0.0, 0.0, 0.0], #2
             [1/3, 1/2, 1.0, 1/2, 0.0, 0.0, 0.0, 0.0], #3
             [0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 0.0, 0.0], #4
             [1/3, 1/2, 0.0, 1/2, 0.0, 0.0, 0.0, 0.0], #5
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0], #6
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 1.0], #7
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 1/2, 0.0]  #8
            ])

#Ajuste 2: Ajustar o nó absorvente como já foi explicado (ajuste 1) e somar algebricamente por uma matriz (K) de probabilidades iguais para cada linha e coluna. A matriz P terá peso 0.85 e a matriz K, 0.15 (Parâmetros usados pela Google)

# Vale lembrar que a parte ajustada deve ser referente somente ao cluster que contém o nó absorvente, nesse caso, o bloco P11
#                      1|   2|   3|   4|   5|   6|   7|   8
P_ajuste= np.array([[0.0, 0.0, 1/5, 0.0, 0.0, 0.0, 0.0, 0.0], #1
                    [1/3, 0.0, 1/5, 0.0, 1/2, 0.0, 0.0, 0.0], #2
                    [1/3, 1/2, 1/5, 1/2, 0.0, 0.0, 0.0, 0.0], #3
                    [0.0, 0.0, 1/5, 0.0, 1/2, 0.0, 0.0, 0.0], #4
                    [1/3, 1/2, 1/5, 1/2, 0.0, 0.0, 0.0, 0.0], #5
                    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0], #6
                    [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 1.0], #7
                    [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 1/2, 0.0]  #8
                   ])

#               1|   2|   3|   4|   5|   6|   7|   8
K= np.array([[1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #1
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #2
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #3
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #4
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #5
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #6
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #7
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8]  #8
            ])

# Realizando o ajuste
p=0.85 #Probabilidade do web surfer seguir hiperlinks (visitar outras páginas)
G = p*P_ajuste+(1-p)*K
print(f'Matriz ajustada:\n{np.round(G,4)}')

# Matriz estacionária pós ajuste
G100 = np.linalg.matrix_power(G,100)

print(f'Matriz estacionária pós ajuste:\n{np.round(G100,4)}')

Matriz ajustada:
[[0.0188 0.0188 0.1888 0.0188 0.0188 0.0188 0.0188 0.0188]
 [0.3021 0.0188 0.1888 0.0188 0.4438 0.0188 0.0188 0.0188]
 [0.3021 0.4438 0.1888 0.4438 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.0188 0.1888 0.0188 0.4438 0.0188 0.0188 0.0188]
 [0.3021 0.4438 0.1888 0.4438 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.0188 0.4438 0.0188]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.4438 0.0188 0.8688]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.4438 0.4438 0.0188]]
Matriz estacionária pós ajuste:
[[0.0469 0.0469 0.0469 0.0469 0.0469 0.0469 0.0469 0.0469]
 [0.1304 0.1304 0.1304 0.1304 0.1304 0.1304 0.1304 0.1304]
 [0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653]
 [0.1171 0.1171 0.1171 0.1171 0.1171 0.1171 0.1171 0.1171]
 [0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653 0.1653]
 [0.0877 0.0877 0.0877 0.0877 0.0877 0.0877 0.0877 0.0877]
 [0.1623 0.1623 0.1623 0.1623 0.1623 0.1623 0.1623 0.1623]
 [0.125  0.125  0.125  0.125  0.125  0.125  0.125  0.125 ]]


## Teste 4

In [24]:
# Questão 1
# Considere uma rede com 7 páginas e com hiperligações representadas por setas no seguinte grafo. 
# Faça o ajuste necessário e determine a página (ou páginas em simultâneo) que têm o ranking mais elevado desta rede.
# Matriz de Markov Ajustada (ajuste 1)
#               1|   2|   3|   4|   5|   6|   7|
P= np.array([[0.0, 1/2, 0.0, 1/2, 1/2, 1/3, 1/7], #1
             [0.0, 0.0, 0.0, 1/2, 0.0, 1/3, 1/7], #2
             [0.0, 0.0, 0.0, 0.0, 1/2, 1/3, 1/7], #3
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1/7], #4
             [0.0, 0.0, 1/2, 0.0, 0.0, 0.0, 1/7], #5
             [1.0, 0.0, 1/2, 0.0, 0.0, 0.0, 1/7], #6
             [0.0, 1/2, 0.0, 0.0, 0.0, 0.0, 1/7], #7
            ])
P100 = np.linalg.matrix_power(P,100)
print(np.round(P100,4))
# R: Página 6

[[0.2273 0.2273 0.2273 0.2273 0.2273 0.2273 0.2273]
 [0.1212 0.1212 0.1212 0.1212 0.1212 0.1212 0.1212]
 [0.1616 0.1616 0.1616 0.1616 0.1616 0.1616 0.1616]
 [0.0101 0.0101 0.0101 0.0101 0.0101 0.0101 0.0101]
 [0.0909 0.0909 0.0909 0.0909 0.0909 0.0909 0.0909]
 [0.3182 0.3182 0.3182 0.3182 0.3182 0.3182 0.3182]
 [0.0707 0.0707 0.0707 0.0707 0.0707 0.0707 0.0707]]


In [25]:
# Questão 2
# Faça os ajustes necessários da matriz para determinar as entradas 1, 4, 5 e 7 do (único) vetor estacionário para a rede WWW da figura.

#               1|   2|   3|   4|   5|   6|   7|   8
P= np.array([[0.0, 0.0, 1/2, 1/4, 0.0, 0.0, 0.0, 0.0], #1
             [1/2, 0.0, 1/2, 1/4, 0.0, 0.0, 0.0, 0.0], #2
             [1/2, 1/2, 0.0, 1/4, 0.0, 0.0, 0.0, 0.0], #3
             [0.0, 0.0, 0.0, 1/4, 0.0, 0.0, 0.0, 0.0], #4
#----------------------------------------------------Separando clusters
             [0.0, 1/2, 0.0, 0.0, 0.0, 1/3, 1.0, 1/4], #5
             [0.0, 0.0, 0.0, 0.0, 1/2, 0.0, 0.0, 1/4], #6
             [0.0, 0.0, 0.0, 0.0, 1/2, 1/3, 0.0, 1/4], #7
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/3, 0.0, 1/4]  #8
            ])
#               1|   2|   3|   4|   5|   6|   7|   8
K= np.array([[1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #1
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #2
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #3
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #4
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #5
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #6
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8], #7
             [1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8, 1/8]  #8
            ])

# Realizando o ajuste
p=0.85
G = p*P+(1-p)*K
print(f'Matriz ajustada:\n{np.round(G,4)}')

# Matriz estacionária pós ajuste
G100 = np.linalg.matrix_power(G,10000)
print(f'Matriz estacionária:\n{np.round(G100,4)}')

# Errei essa, não sei resolver

Matriz ajustada:
[[0.0188 0.0188 0.4438 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.4438 0.0188 0.4438 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.4438 0.4438 0.0188 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.0188 0.0188 0.2312 0.0188 0.0188 0.0188 0.0188]
 [0.0188 0.4438 0.0188 0.0188 0.0188 0.3021 0.8688 0.2312]
 [0.0188 0.0188 0.0188 0.0188 0.4438 0.0188 0.0188 0.2312]
 [0.0188 0.0188 0.0188 0.0188 0.4438 0.3021 0.0188 0.2312]
 [0.0188 0.0188 0.0188 0.0188 0.0188 0.3021 0.0188 0.2312]]
Matriz estacionária:
[[0.0604 0.0604 0.0604 0.0604 0.0604 0.0604 0.0604 0.0604]
 [0.086  0.086  0.086  0.086  0.086  0.086  0.086  0.086 ]
 [0.086  0.086  0.086  0.086  0.086  0.086  0.086  0.086 ]
 [0.0238 0.0238 0.0238 0.0238 0.0238 0.0238 0.0238 0.0238]
 [0.2941 0.2941 0.2941 0.2941 0.2941 0.2941 0.2941 0.2941]
 [0.1611 0.1611 0.1611 0.1611 0.1611 0.1611 0.1611 0.1611]
 [0.2068 0.2068 0.2068 0.2068 0.2068 0.2068 0.2068 0.2068]
 [0.0818 0.0818 0.0818 0.0818 0.0818 0.0818 0.0818 0.0818]]


# Teste Final

In [26]:
#Questão 1
# Considere o seguinte modelo de mobilidade da população numa dada região. 
# Cada ano, 45% da população da cidade desloca-se para viver nos arredores. 
# Por outro lado, anualmente, 50% da população que vive nos arredores passa a viver na cidade.

# Matriz de mobilidade:
#               C|     A 
M= np.array([[0.45,0.5], # C
             [0.55,0.5]  # A
            ]) 

# População em 2017
pop_2017= 1000000
# Estado inicial
pop_C = 600000
pop_A = 400000
X0 = np.array([[pop_C],
               [pop_A]
              ])
# Qual a distribuição em 2021?
passo= 4

Dist_21= np.matmul(np.linalg.matrix_power(M,passo),X0)
print(Dist_21)

# Vetor estacionário
M100 = np.linalg.matrix_power(M,100)
print(M100)

[[476191.25]
 [523808.75]]
[[0.47619048 0.47619048]
 [0.52380952 0.52380952]]


In [27]:
# Questão 2
# Em Lisboa durante os meses de inverno o clima é mais imprevisível do que no resto do ano com as seguintes probabilidades:
# Se houve um dia de sol, a probabilidade de no dia seguinte continuar a haver sol é 0.1 de passar a estar nublado é de 0.55 e de estar a chover é de 0.35
# Se houve um dia nublado, a probabilidade de no dia seguinte haver sol é 0.6 de continuar nublado é de 0.15 e de estar a chover é de 0.25
# Se houve um dia de chuva, a probabilidade de no dia seguinte haver sol é 0.3 de estar nublado é de 0.6 e da chuva se prolongar é 0.1
# Calcule as probabilidades a longo prazo para os diferentes tipos de tempo num dia de inverno lisboeta.

#                S|  N|  C|
M = np.array([[.10,.60,.30], #S
              [.55,.15,.60], #N
              [.35,.25,.10]  #C
             ])
print(M)
# Probabilidade a longo prazo
M100= np.linalg.matrix_power(M,100)
print(np.round(M100,4))

[[0.1  0.6  0.3 ]
 [0.55 0.15 0.6 ]
 [0.35 0.25 0.1 ]]
[[0.3504 0.3504 0.3504]
 [0.4017 0.4017 0.4017]
 [0.2479 0.2479 0.2479]]


In [28]:
# Questão 3
# Considere o labirinto com 5 salas da figura.
# Assumindo que um rato transita de sala equiprovavelmente a cada contagem do tempo, qual a probabilidade deste se encontrar na sala 3 após 2 transições, sabendo que partiu da sala 1.

# Matriz de markov
#              1 |  2|  3|  4| 5
M= np.array([[0.0,1/3,1/2,1/4,0.0], #1
             [1/3,0.0,0.0,1/4,1/2], #2
             [1/3,0.0,0.0,1/4,0.0], #3
             [1/3,1/3,1/2,0.0,1/2], #4
             [0.0,1/3,0.0,1/4,0.0]  #5
            ])
# Após 2 transcições
M2 = np.linalg.matrix_power(M,2)

print(f'Matriz de Markov:\n{np.round(M,2)}\n\nApós 2 Transações:\n{np.round(M2,2)}')
print(f'\nProbabilidade:{round(M2[2][0]*100,2)}%')

Matriz de Markov:
[[0.   0.33 0.5  0.25 0.  ]
 [0.33 0.   0.   0.25 0.5 ]
 [0.33 0.   0.   0.25 0.  ]
 [0.33 0.33 0.5  0.   0.5 ]
 [0.   0.33 0.   0.25 0.  ]]

Após 2 Transações:
[[0.36 0.08 0.12 0.21 0.29]
 [0.08 0.36 0.29 0.21 0.12]
 [0.08 0.19 0.29 0.08 0.12]
 [0.28 0.28 0.17 0.42 0.17]
 [0.19 0.08 0.12 0.08 0.29]]

Probabilidade:8.33%


In [29]:
# Questão 4
# Considere a seguinte rede social, composta por 2 grupos de utilizadores.
# Sabendo que existe uma probabilidade 0.4 de um utilizador da rede social visitar qualquer utilizador da rede, qual a probabilidade do utilizador B terminar a sua navegação na página do utilizador D passadas 4 visitas?

#               A|   B|   C|   D|   E|   F|   G
P= np.array([[0.0, 1/2, 0.0, 0.0, 0.0, 0.0, 0.0], #A
             [1/2, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], #B
             [1/2, 1/2, 0.0, 0.0, 0.0, 0.0, 0.0], #C
             [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], #D
             [0.0, 0.0, 0.0, 0.0, 0.0, 1/2, 1.0], #E
             [0.0, 0.0, 0.0, 1/2, 1.0, 0.0, 0.0], #F
             [0.0, 0.0, 0.0, 1/2, 0.0, 1/2, 0.0]  #G
            ])

#               A|   B|   C|   D|   E|   F|   G
K= np.array([[1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7], #A
             [1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7], #B
             [1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7], #C
             [1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7], #D
             [1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7], #E
             [1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7], #F
             [1/7, 1/7, 1/7, 1/7, 1/7, 1/7, 1/7]  #G
            ])

# Ajuste para linkar os clusters
p=0.40
G= p*P + (1-p)*K
print(np.round(G,4))

# Após 4 visitas
G4 = np.linalg.matrix_power(G,4)
print(f'\nApós 4 visitas:\n{np.round(G4,4)}')
print(f'\nProbabilidade:{round(G4[3][1]*100,2)}%')

[[0.0857 0.2857 0.0857 0.0857 0.0857 0.0857 0.0857]
 [0.2857 0.0857 0.4857 0.0857 0.0857 0.0857 0.0857]
 [0.2857 0.2857 0.0857 0.0857 0.0857 0.0857 0.0857]
 [0.0857 0.0857 0.0857 0.0857 0.0857 0.0857 0.0857]
 [0.0857 0.0857 0.0857 0.0857 0.0857 0.2857 0.4857]
 [0.0857 0.0857 0.0857 0.2857 0.4857 0.0857 0.0857]
 [0.0857 0.0857 0.0857 0.2857 0.0857 0.2857 0.0857]]

Após 4 visitas:
[[0.1214 0.1198 0.1262 0.1166 0.1166 0.1166 0.1166]
 [0.1746 0.1762 0.1682 0.1618 0.1618 0.1618 0.1618]
 [0.1472 0.1472 0.1488 0.1392 0.1392 0.1392 0.1392]
 [0.0857 0.0857 0.0857 0.0857 0.0857 0.0857 0.0857]
 [0.1694 0.1694 0.1694 0.179  0.1758 0.1822 0.1822]
 [0.1673 0.1673 0.1673 0.1737 0.1801 0.1737 0.1801]
 [0.1344 0.1344 0.1344 0.144  0.1408 0.1408 0.1344]]

Probabilidade:8.57%
